services:
  booklibrary.api:
    image: booklibrary.api
    build:
      context: .
      dockerfile: BookLibrary.API/Dockerfile
      
  booklibrary.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: admin@123
    ports:
      - "1433:1433"
